version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each
        columns:
          - name: date_date, orders_id, pdti_id, revenue, quantity
            description: Primary key of the table
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
